FROM docker.io/debian:jessie

ENV DEBIAN_FRONTEND noninteractive

RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/50no-install-recommends
RUN echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/50no-install-suggests

COPY project.tar /tmp

WORKDIR /var/www/

RUN tar -xvf /tmp/project.tar && chown -R root:root /var/www

RUN set -x \
 && apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install \
    python3 \
    python3-chardet \
    python3-colorama \
    python3-html5lib \
    python3-pkg-resources \
    python3-requests \
    python3-six \
    python3-urllib3 \
    libgeos-c1 \
    make \
    python3-dev \
    python3-pip \
    libgeos-dev \
    nodejs-legacy \
    npm \
    openjdk-7-jdk \
    gettext \
    gcc \
    git \
    virtualenv \
 && make -f config/dev install \
 && py3compile -f -X '^.*gevent/_util_py2.py$' .build/venv/ \
 && rm -fr .cache/ .npm/ /root/.cache/ /root/.npm/ \
 && apt-get -y purge \
    python3-dev \
    python3-pip \
    libgeos-dev \
    nodejs-legacy \
    npm \
    openjdk-7-jdk \
    gettext \
    gcc \
    git \
    virtualenv \
 && apt-get -y --purge autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV version="{version}" \
    PATH=/var/www/.build/venv/bin/:$PATH

COPY /docker-entrypoint.sh /
COPY /docker-entrypoint.d/* /docker-entrypoint.d/
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8080
CMD ["gunicorn", "--paste", "production.ini", "-u", "www-data", "-g", "www-data", "-b", ":8080"]

