FROM docker.io/debian:jessie

ENV DEBIAN_FRONTEND noninteractive

RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/50no-install-recommends
RUN echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/50no-install-suggests

ADD project.tar /var/www

WORKDIR /var/www/

RUN set -x \
 && apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install \
    python3 \
    python3-chardet \
    python3-colorama \
    python3-html5lib \
    python3-pkg-resources \
    python3-requests \
    python3-six \
    python3-urllib3 \
    libgeos-c1 \
    make \
    python3-dev \
    python3-pip \
    libgeos-dev \
    nodejs-legacy \
    npm \
    openjdk-7-jdk \
    gettext \
    gcc \
    git \
    virtualenv \
 && make -f config/dev install \
 && apt-get -y --purge autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV PATH=/var/www/.build/venv/bin/:$PATH

COPY /docker-entrypoint.sh /
COPY /docker-entrypoint.d/* /docker-entrypoint.d/
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["make", "-f", "config/docker", "serve"]

