/**********************************************************************
 * Extern for jsts
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var jsts = {
  "geom": {
    "GeometryCollection": {},
    "GeometryFactory": {}
  },
  "io": {
    "OL3Parser": function () {}
  }
};

jsts.geom.GeometryCollection;
jsts.io.OL3Parser;
jsts.geom.GeometryCollection.prototype = {
  "union": function () {},
};
jsts.geom.GeometryFactory.prototype = {
  "createGeometryCollection": function () {},
};
jsts.io.OL3Parser.prototype = {
  "read": function () {},
  "write": function () {}
};
